### PR TITLE
fix(external): peerDependencies should also be external

### PR DESCRIPTION
**Pull request by stevemao**
See https://github.com/webcomponents/react-integration/pull/33/files#r76906777

### CODE REVIEW

**Comment by treshugart** [comment]
lgtm

**Comment by treshugart** [comment]
It might be  good idea to bump this as a "feat" instead of a "fix". Not sure if this is classified as a bug. Not too fussed, though.

**Comment by bengummer** [comment]
lgtm

**Comment by bengummer** [comment]
hey @stevemao it looks like you need to update your branch from master before this can be merged.

**Comment by stevemao** [comment]
done

**Pull request merged**
