### PR TITLE
feat(testing): switch to testingbot

### PR DESCRIPTION
**Pull request by bengummer**

### CODE REVIEW

**Comment by bengummer** [comment]
@treshugart i've disabled iOS for now until TestingBot reply. I've also loaded the `TESTINGBOT_*` creds into the skatejs env vars so should be good to merge.

**Comment by mtscrb** [comment]
lgtm

**Comment by treshugart** [comment]
:shipit:

**Comment by treshugart** [comment]
lgtm

**Comment by treshugart** [comment]
lgtm

**Pull request merged**
